#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum ParamType {
    Integer,
    Float,
    Bool,
    String,
    Enum(&'static [&'static str]),
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct ParamDef {
    pub key: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub param_type: ParamType,
    pub default_display: &'static str,
    pub category: &'static str,
    pub is_typed_field: bool,
}

pub static PARAMS: &[ParamDef] = &[
    // ── Context ──────────────────────────────────────────────────────────────
    ParamDef {
        key: "n_ctx",
        label: "Context Size",
        description: "Maximum context window size (0=auto from model)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_predict",
        label: "Max Tokens",
        description: "Maximum tokens to predict (-1=unlimited)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_batch",
        label: "Batch Size",
        description: "Logical batch size for prompt processing",
        param_type: ParamType::Integer,
        default_display: "512",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_ubatch",
        label: "Micro-batch Size",
        description: "Physical batch size for prompt processing",
        param_type: ParamType::Integer,
        default_display: "512",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "keep",
        label: "Keep Tokens",
        description: "Tokens to keep from initial prompt (0=none, -1=all)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "flash_attn",
        label: "Flash Attention",
        description: "Flash attention mode",
        param_type: ParamType::Enum(&["auto", "on", "off"]),
        default_display: "auto",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "cache_type_k",
        label: "KV Cache Type K",
        description: "Data type for key cache (f32, f16, bf16, q8_0, q4_0, q4_1, iq4_nl, q5_0, q5_1)",
        param_type: ParamType::Enum(&["f32", "f16", "bf16", "q8_0", "q4_0", "q4_1", "iq4_nl", "q5_0", "q5_1"]),
        default_display: "f16",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "cache_type_v",
        label: "KV Cache Type V",
        description: "Data type for value cache (f32, f16, bf16, q8_0, q4_0, q4_1, iq4_nl, q5_0, q5_1)",
        param_type: ParamType::Enum(&["f32", "f16", "bf16", "q8_0", "q4_0", "q4_1", "iq4_nl", "q5_0", "q5_1"]),
        default_display: "f16",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "swa-full",
        label: "SWA Full",
        description: "Use full-size sliding window attention cache",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-kv-offload",
        label: "No KV Offload",
        description: "Disable KV cache offload to GPU",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "context-shift",
        label: "Context Shift",
        description: "Use context shift on infinite text generation",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-cache-prompt",
        label: "No Cache Prompt",
        description: "Disable prompt caching",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "cache-reuse",
        label: "Cache Reuse",
        description: "Min chunk for KV shifting reuse (0=disabled)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "cache-ram",
        label: "Cache RAM (MiB)",
        description: "Max cache size (-1=no limit, 0=disabled, default: 8192)",
        param_type: ParamType::Integer,
        default_display: "8192",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "ctx-checkpoints",
        label: "Context Checkpoints",
        description: "Max checkpoints per slot (default: 32)",
        param_type: ParamType::Integer,
        default_display: "32",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "ctx-checkpoint-interval",
        label: "Checkpoint Interval",
        description: "Checkpoint interval in tokens (default: 256)",
        param_type: ParamType::Integer,
        default_display: "256",
        category: "Context",
        is_typed_field: false,
    },

    // ── Hardware ─────────────────────────────────────────────────────────────
    ParamDef {
        key: "n_gpu_layers",
        label: "GPU Layers",
        description: "Number of layers to offload to GPU (-1=all, 0=none)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_threads",
        label: "CPU Threads",
        description: "Number of CPU threads for generation",
        param_type: ParamType::Integer,
        default_display: "auto",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "split-mode",
        label: "Split Mode",
        description: "Multi-GPU split mode",
        param_type: ParamType::Enum(&["none", "layer", "row"]),
        default_display: "layer",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "tensor-split",
        label: "Tensor Split",
        description: "Comma-separated proportions for multi-GPU split",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "main-gpu",
        label: "Main GPU",
        description: "Main GPU index for computation",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "device",
        label: "Device",
        description: "Device specification",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "mlock",
        label: "Memory Lock",
        description: "Lock model memory to prevent swapping",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "no_mmap",
        label: "No Memory Map",
        description: "Disable memory mapping, load model into RAM",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "direct-io",
        label: "Direct IO",
        description: "Use direct I/O for model loading",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "threads-batch",
        label: "Threads Batch",
        description: "Number of threads for batch processing",
        param_type: ParamType::Integer,
        default_display: "auto",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "numa",
        label: "NUMA",
        description: "NUMA optimization strategy",
        param_type: ParamType::Enum(&["disabled", "distribute", "isolate", "numactl", "mirror"]),
        default_display: "disabled",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "cpu-moe",
        label: "CPU MoE",
        description: "Use CPU for MoE layers",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "n-cpu-moe-layers",
        label: "N CPU MoE Layers",
        description: "Number of MoE layers to run on CPU",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "repack",
        label: "Repack",
        description: "Repack quantized tensors for performance",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "op-offload",
        label: "Op Offload",
        description: "Offload operations to GPU",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-host-buffer",
        label: "No Host Buffer",
        description: "Disable host buffer for GPU offloading",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "check-tensors",
        label: "Check Tensors",
        description: "Check tensor data for validity",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "override-tensor",
        label: "Override Tensor",
        description: "Override tensor type mapping (name=type)",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "override-kv",
        label: "Override KV",
        description: "Override KV metadata (key=type:value)",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "fit",
        label: "Fit",
        description: "Auto-fit model to available memory",
        param_type: ParamType::Enum(&["on", "off"]),
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "fit-target",
        label: "Fit Target (MiB)",
        description: "Target memory usage for auto-fit",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "fit-min-ctx",
        label: "Fit Min Ctx",
        description: "Minimum context size for auto-fit",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },

    // ── Sampling ─────────────────────────────────────────────────────────────
    ParamDef {
        key: "temperature",
        label: "Temperature",
        description: "Sampling temperature (0=greedy, higher=more random)",
        param_type: ParamType::Float,
        default_display: "0.8",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "seed",
        label: "Seed",
        description: "Random seed (-1=random)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "top_k",
        label: "Top-K",
        description: "Top-K sampling (0=disabled)",
        param_type: ParamType::Integer,
        default_display: "40",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "top_p",
        label: "Top-P",
        description: "Top-P (nucleus) sampling",
        param_type: ParamType::Float,
        default_display: "0.95",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "min_p",
        label: "Min-P",
        description: "Min-P sampling threshold",
        param_type: ParamType::Float,
        default_display: "0.05",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "samplers",
        label: "Samplers",
        description: "Sampler chain order (e.g. top_k;top_p;min_p;temperature)",
        param_type: ParamType::String,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "top-n-sigma",
        label: "Top-N-Sigma",
        description: "Top-N-Sigma sampling threshold",
        param_type: ParamType::Float,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "typical",
        label: "Typical P",
        description: "Typical-P sampling threshold (1.0=disabled)",
        param_type: ParamType::Float,
        default_display: "1.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "repeat-last-n",
        label: "Repeat Last N",
        description: "Repetition penalty window (-1=ctx, 0=disabled)",
        param_type: ParamType::Integer,
        default_display: "64",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "repeat-penalty",
        label: "Repeat Penalty",
        description: "Repetition penalty (1.0=disabled)",
        param_type: ParamType::Float,
        default_display: "1.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "presence-penalty",
        label: "Presence Penalty",
        description: "Presence penalty (0.0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "frequency-penalty",
        label: "Frequency Penalty",
        description: "Frequency penalty (0.0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "xtc-probability",
        label: "XTC Probability",
        description: "XTC probability of removing a top token",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "xtc-threshold",
        label: "XTC Threshold",
        description: "XTC minimum probability threshold",
        param_type: ParamType::Float,
        default_display: "0.1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-multiplier",
        label: "DRY Multiplier",
        description: "DRY penalty multiplier (0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-base",
        label: "DRY Base",
        description: "DRY penalty base value",
        param_type: ParamType::Float,
        default_display: "1.75",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-allowed-length",
        label: "DRY Allowed Length",
        description: "DRY allowed repeat length",
        param_type: ParamType::Integer,
        default_display: "1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-penalty-last-n",
        label: "DRY Penalty Last N",
        description: "DRY penalty lookback (-1=ctx, 0=disabled)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "mirostat",
        label: "Mirostat Mode",
        description: "Mirostat sampling (0=disabled, 1=v1, 2=v2)",
        param_type: ParamType::Enum(&["0", "1", "2"]),
        default_display: "0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "mirostat-lr",
        label: "Mirostat LR",
        description: "Mirostat learning rate",
        param_type: ParamType::Float,
        default_display: "0.1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "mirostat-ent",
        label: "Mirostat Entropy",
        description: "Mirostat target entropy",
        param_type: ParamType::Float,
        default_display: "5.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dynatemp-range",
        label: "Dynamic Temp Range",
        description: "Dynamic temperature range (0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dynatemp-exponent",
        label: "Dynamic Temp Exponent",
        description: "Dynamic temperature exponent",
        param_type: ParamType::Float,
        default_display: "1.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-escape",
        label: "Ignore EOS",
        description: "Ignore end-of-sequence token",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "backend-sampling",
        label: "Backend Sampling",
        description: "Use backend-optimized sampling",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "adaptive-target",
        label: "Adaptive Target",
        description: "Adaptive sampling target",
        param_type: ParamType::Float,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "adaptive-decay",
        label: "Adaptive Decay",
        description: "Adaptive sampling decay rate",
        param_type: ParamType::Float,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },

    // ── Server ───────────────────────────────────────────────────────────────
    ParamDef {
        key: "host",
        label: "Host",
        description: "Server listen address",
        param_type: ParamType::String,
        default_display: "127.0.0.1",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "port",
        label: "Port",
        description: "Server listen port",
        param_type: ParamType::Integer,
        default_display: "8080",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "parallel",
        label: "Parallel Slots",
        description: "Number of parallel request slots",
        param_type: ParamType::Integer,
        default_display: "1",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "cont_batching",
        label: "Continuous Batching",
        description: "Enable continuous batching",
        param_type: ParamType::Bool,
        default_display: "on",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "timeout",
        label: "Timeout",
        description: "Server request timeout in seconds",
        param_type: ParamType::Integer,
        default_display: "600",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "threads-http",
        label: "HTTP Threads",
        description: "Number of HTTP server threads",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "api-key",
        label: "API Key",
        description: "Comma-separated authentication keys",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "api-key-file",
        label: "API Key File",
        description: "File containing API keys (one per line)",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "alias",
        label: "Model Alias",
        description: "Model alias for API responses",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-webui",
        label: "No WebUI",
        description: "Disable built-in web UI",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "metrics",
        label: "Metrics",
        description: "Enable Prometheus metrics endpoint",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "props",
        label: "Props",
        description: "Enable /props endpoint",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "slots",
        label: "Slots Endpoint",
        description: "Enable /slots endpoint",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "embedding",
        label: "Embedding",
        description: "Enable embedding mode",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "reranking",
        label: "Reranking",
        description: "Enable reranking mode",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-warmup",
        label: "No Warmup",
        description: "Disable model warmup on startup",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "slot-prompt-similarity",
        label: "Slot Prompt Similarity",
        description: "Similarity threshold for slot reuse",
        param_type: ParamType::Float,
        default_display: "0.5",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "sleep-idle",
        label: "Sleep Idle",
        description: "Seconds of idle before sleeping (-1=disabled)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "ssl-key-file",
        label: "SSL Key File",
        description: "Path to SSL private key file",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "ssl-cert-file",
        label: "SSL Cert File",
        description: "Path to SSL certificate file",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },

    // ── Chat ─────────────────────────────────────────────────────────────────
    ParamDef {
        key: "chat-template",
        label: "Chat Template",
        description: "Jinja chat template string",
        param_type: ParamType::String,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "chat-template-file",
        label: "Chat Template File",
        description: "Path to Jinja chat template file",
        param_type: ParamType::String,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "jinja",
        label: "Jinja",
        description: "Enable Jinja template engine",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "reasoning-format",
        label: "Reasoning Format",
        description: "Reasoning output format",
        param_type: ParamType::Enum(&["none", "deepseek", "default"]),
        default_display: "none",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "reasoning-budget",
        label: "Reasoning Budget",
        description: "Max tokens for reasoning",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },

    // ── Advanced: RoPE ───────────────────────────────────────────────────────
    ParamDef {
        key: "rope-scaling",
        label: "RoPE Scaling",
        description: "RoPE scaling type",
        param_type: ParamType::Enum(&["default", "none", "linear", "yarn"]),
        default_display: "default",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "rope-scale",
        label: "RoPE Scale",
        description: "RoPE context scaling factor",
        param_type: ParamType::Float,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "rope-freq-base",
        label: "RoPE Freq Base",
        description: "RoPE frequency base (0=auto from model)",
        param_type: ParamType::Float,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "rope-freq-scale",
        label: "RoPE Freq Scale",
        description: "RoPE frequency scaling factor (0=auto from model)",
        param_type: ParamType::Float,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: Speculative ────────────────────────────────────────────────
    ParamDef {
        key: "model-draft",
        label: "Draft Model",
        description: "Path to draft model for speculative decoding",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "draft-max",
        label: "Draft Max",
        description: "Max draft tokens per step",
        param_type: ParamType::Integer,
        default_display: "16",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "draft-min",
        label: "Draft Min",
        description: "Min draft tokens per step",
        param_type: ParamType::Integer,
        default_display: "5",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "draft-p-min",
        label: "Draft P Min",
        description: "Min draft token probability",
        param_type: ParamType::Float,
        default_display: "0.9",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: LoRA ───────────────────────────────────────────────────────
    ParamDef {
        key: "lora",
        label: "LoRA",
        description: "Path to LoRA adapter file",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "lora-scaled",
        label: "LoRA Scaled",
        description: "LoRA adapter with scale (path:scale)",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: Multimodal ─────────────────────────────────────────────────
    ParamDef {
        key: "mmproj",
        label: "Multimodal Projector",
        description: "Path to mmproj file for vision models",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "mmproj-url",
        label: "mmproj URL",
        description: "URL to download mmproj file",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: Logging ────────────────────────────────────────────────────
    ParamDef {
        key: "log-file",
        label: "Log File",
        description: "Path to log file",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "verbosity",
        label: "Verbosity",
        description: "Log verbosity level (0-4)",
        param_type: ParamType::Enum(&["0", "1", "2", "3", "4"]),
        default_display: "0",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "verbose",
        label: "Verbose",
        description: "Enable verbose output",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Raw ──────────────────────────────────────────────────────────────────
    ParamDef {
        key: "__raw__",
        label: "Raw CLI Arguments",
        description: "Free-form CLI arguments not covered above",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
];
