#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum ParamType {
    Integer,
    Float,
    Bool,
    String,
    Enum(&'static [&'static str]),
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct ParamDef {
    pub key: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub param_type: ParamType,
    pub default_display: &'static str,
    pub category: &'static str,
    pub is_typed_field: bool,
}

pub static PARAMS: &[ParamDef] = &[
    // ── Context ──────────────────────────────────────────────────────────────
    ParamDef {
        key: "n_ctx",
        label: "Context Size",
        description: "Maximum context window size (0=auto from model)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_predict",
        label: "Max Tokens",
        description: "Maximum tokens to predict (-1=unlimited)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_batch",
        label: "Batch Size",
        description: "Logical batch size for prompt processing",
        param_type: ParamType::Integer,
        default_display: "512",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_ubatch",
        label: "Micro-batch Size",
        description: "Physical batch size for prompt processing",
        param_type: ParamType::Integer,
        default_display: "512",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "keep",
        label: "Keep Tokens",
        description: "Tokens to keep from initial prompt (0=none, -1=all)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "flash_attn",
        label: "Flash Attention",
        description: "Flash attention mode",
        param_type: ParamType::Enum(&["auto", "on", "off"]),
        default_display: "auto",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "cache_type_k",
        label: "KV Cache Type K",
        description: "Data type for key cache (f32, f16, bf16, q8_0, q4_0, q4_1, iq4_nl, q5_0, q5_1)",
        param_type: ParamType::Enum(&["f32", "f16", "bf16", "q8_0", "q4_0", "q4_1", "iq4_nl", "q5_0", "q5_1"]),
        default_display: "f16",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "cache_type_v",
        label: "KV Cache Type V",
        description: "Data type for value cache (f32, f16, bf16, q8_0, q4_0, q4_1, iq4_nl, q5_0, q5_1)",
        param_type: ParamType::Enum(&["f32", "f16", "bf16", "q8_0", "q4_0", "q4_1", "iq4_nl", "q5_0", "q5_1"]),
        default_display: "f16",
        category: "Context",
        is_typed_field: true,
    },
    ParamDef {
        key: "swa-full",
        label: "SWA Full",
        description: "Use full-size sliding window attention cache",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-kv-offload",
        label: "No KV Offload",
        description: "Disable KV cache offload to GPU",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "kv-unified",
        label: "KV Unified",
        description: "Use single unified KV buffer shared across sequences",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "context-shift",
        label: "Context Shift",
        description: "Use context shift on infinite text generation",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-cache-prompt",
        label: "No Cache Prompt",
        description: "Disable prompt caching",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "cache-reuse",
        label: "Cache Reuse",
        description: "Min chunk for KV shifting reuse (0=disabled)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "cache-ram",
        label: "Cache RAM (MiB)",
        description: "Max cache size (-1=no limit, 0=disabled, default: 8192)",
        param_type: ParamType::Integer,
        default_display: "8192",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "ctx-checkpoints",
        label: "Context Checkpoints",
        description: "Max checkpoints per slot (default: 32)",
        param_type: ParamType::Integer,
        default_display: "32",
        category: "Context",
        is_typed_field: false,
    },
    ParamDef {
        key: "checkpoint-every-n-tokens",
        label: "Checkpoint Interval",
        description: "Checkpoint every N tokens (default: 8192, -1=disable)",
        param_type: ParamType::Integer,
        default_display: "8192",
        category: "Context",
        is_typed_field: false,
    },

    // ── Hardware ─────────────────────────────────────────────────────────────
    ParamDef {
        key: "n_gpu_layers",
        label: "GPU Layers",
        description: "Number of layers to offload to GPU (-1=all, 0=none)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "n_threads",
        label: "CPU Threads",
        description: "Number of CPU threads for generation",
        param_type: ParamType::Integer,
        default_display: "auto",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "split-mode",
        label: "Split Mode",
        description: "Multi-GPU split mode",
        param_type: ParamType::Enum(&["none", "layer", "row"]),
        default_display: "layer",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "tensor-split",
        label: "Tensor Split",
        description: "Comma-separated proportions for multi-GPU split",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "main-gpu",
        label: "Main GPU",
        description: "Main GPU index for computation",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "device",
        label: "Device",
        description: "Device specification, comma-separated",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "mlock",
        label: "Memory Lock",
        description: "Lock model memory to prevent swapping",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "no_mmap",
        label: "No Memory Map",
        description: "Disable memory mapping, load model into RAM",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: true,
    },
    ParamDef {
        key: "direct-io",
        label: "Direct IO",
        description: "Use direct I/O for model loading",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "threads-batch",
        label: "Threads Batch",
        description: "Number of threads for batch processing",
        param_type: ParamType::Integer,
        default_display: "auto",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "numa",
        label: "NUMA",
        description: "NUMA optimization strategy",
        param_type: ParamType::Enum(&["disabled", "distribute", "isolate", "numactl", "mirror"]),
        default_display: "disabled",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "cpu-moe",
        label: "CPU MoE",
        description: "Keep all MoE weights on CPU",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "n-cpu-moe",
        label: "N CPU MoE Layers",
        description: "Keep MoE weights of first N layers on CPU",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-repack",
        label: "No Repack",
        description: "Disable weight repacking (repacking is on by default)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-op-offload",
        label: "No Op Offload",
        description: "Disable host tensor operation offload to device (offload is on by default)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-host",
        label: "No Host Buffer",
        description: "Bypass host buffer to allow extra device buffers",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "check-tensors",
        label: "Check Tensors",
        description: "Check tensor data for validity on load",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "override-tensor",
        label: "Override Tensor",
        description: "Override tensor buffer type: <pattern>=<type>,...",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "override-kv",
        label: "Override KV",
        description: "Override KV metadata: KEY=TYPE:VALUE,...",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "fit",
        label: "Fit",
        description: "Auto-fit model parameters to available device memory",
        param_type: ParamType::Enum(&["on", "off"]),
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "fit-target",
        label: "Fit Target (MiB)",
        description: "Target free memory margin per device (default: 1024 MiB)",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "fit-ctx",
        label: "Fit Min Ctx",
        description: "Minimum context size when using --fit (default: 4096)",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "cpu-moe-draft",
        label: "CPU MoE (Draft)",
        description: "Keep all MoE weights on CPU for draft model",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "n-cpu-moe-draft",
        label: "N CPU MoE Layers (Draft)",
        description: "Keep MoE weights of first N layers on CPU for draft model",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "cpu-mask",
        label: "CPU Mask",
        description: "CPU affinity mask in hexadecimal",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "cpu-range",
        label: "CPU Range",
        description: "CPU affinity range: lo-hi",
        param_type: ParamType::String,
        default_display: "",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "cpu-strict",
        label: "CPU Strict",
        description: "Use strict CPU affinity (0=off, 1=on)",
        param_type: ParamType::Enum(&["0", "1"]),
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "prio",
        label: "Priority",
        description: "Process priority (-1=low, 0=normal, 1=medium, 2=high, 3=realtime)",
        param_type: ParamType::Enum(&["-1", "0", "1", "2", "3"]),
        default_display: "0",
        category: "Hardware",
        is_typed_field: false,
    },
    ParamDef {
        key: "poll",
        label: "Poll",
        description: "Polling level 0-100 (default: 50)",
        param_type: ParamType::Integer,
        default_display: "50",
        category: "Hardware",
        is_typed_field: false,
    },

    // ── Sampling ─────────────────────────────────────────────────────────────
    ParamDef {
        key: "temperature",
        label: "Temperature",
        description: "Sampling temperature (0=greedy, higher=more random)",
        param_type: ParamType::Float,
        default_display: "0.8",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "seed",
        label: "Seed",
        description: "Random seed (-1=random)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "top_k",
        label: "Top-K",
        description: "Top-K sampling (0=disabled)",
        param_type: ParamType::Integer,
        default_display: "40",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "top_p",
        label: "Top-P",
        description: "Top-P (nucleus) sampling",
        param_type: ParamType::Float,
        default_display: "0.95",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "min_p",
        label: "Min-P",
        description: "Min-P sampling threshold",
        param_type: ParamType::Float,
        default_display: "0.05",
        category: "Sampling",
        is_typed_field: true,
    },
    ParamDef {
        key: "samplers",
        label: "Samplers",
        description: "Sampler chain order (e.g. top_k;top_p;min_p;temperature)",
        param_type: ParamType::String,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "top-n-sigma",
        label: "Top-N-Sigma",
        description: "Top-N-Sigma sampling threshold",
        param_type: ParamType::Float,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "typical",
        label: "Typical P",
        description: "Typical-P sampling threshold (1.0=disabled)",
        param_type: ParamType::Float,
        default_display: "1.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "repeat-last-n",
        label: "Repeat Last N",
        description: "Repetition penalty window (-1=ctx, 0=disabled)",
        param_type: ParamType::Integer,
        default_display: "64",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "repeat-penalty",
        label: "Repeat Penalty",
        description: "Repetition penalty (1.0=disabled)",
        param_type: ParamType::Float,
        default_display: "1.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "presence-penalty",
        label: "Presence Penalty",
        description: "Presence penalty (0.0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "frequency-penalty",
        label: "Frequency Penalty",
        description: "Frequency penalty (0.0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "xtc-probability",
        label: "XTC Probability",
        description: "XTC probability of removing a top token",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "xtc-threshold",
        label: "XTC Threshold",
        description: "XTC minimum probability threshold",
        param_type: ParamType::Float,
        default_display: "0.1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-multiplier",
        label: "DRY Multiplier",
        description: "DRY penalty multiplier (0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-base",
        label: "DRY Base",
        description: "DRY penalty base value",
        param_type: ParamType::Float,
        default_display: "1.75",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-allowed-length",
        label: "DRY Allowed Length",
        description: "DRY allowed repeat length",
        param_type: ParamType::Integer,
        default_display: "1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dry-penalty-last-n",
        label: "DRY Penalty Last N",
        description: "DRY penalty lookback (-1=ctx, 0=disabled)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "mirostat",
        label: "Mirostat Mode",
        description: "Mirostat sampling (0=disabled, 1=v1, 2=v2)",
        param_type: ParamType::Enum(&["0", "1", "2"]),
        default_display: "0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "mirostat-lr",
        label: "Mirostat LR",
        description: "Mirostat learning rate",
        param_type: ParamType::Float,
        default_display: "0.1",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "mirostat-ent",
        label: "Mirostat Entropy",
        description: "Mirostat target entropy",
        param_type: ParamType::Float,
        default_display: "5.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dynatemp-range",
        label: "Dynamic Temp Range",
        description: "Dynamic temperature range (0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "dynatemp-exp",
        label: "Dynamic Temp Exponent",
        description: "Dynamic temperature exponent",
        param_type: ParamType::Float,
        default_display: "1.0",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "ignore-eos",
        label: "Ignore EOS",
        description: "Continue generating past end-of-sequence token",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "backend-sampling",
        label: "Backend Sampling",
        description: "Use backend-optimized sampling",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "adaptive-target",
        label: "Adaptive Target",
        description: "Adaptive sampling target probability (negative=disabled)",
        param_type: ParamType::Float,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },
    ParamDef {
        key: "adaptive-decay",
        label: "Adaptive Decay",
        description: "Adaptive sampling decay rate (0.0-0.99)",
        param_type: ParamType::Float,
        default_display: "",
        category: "Sampling",
        is_typed_field: false,
    },

    // ── Server ───────────────────────────────────────────────────────────────
    ParamDef {
        key: "host",
        label: "Host",
        description: "Server listen address",
        param_type: ParamType::String,
        default_display: "127.0.0.1",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "port",
        label: "Port",
        description: "Server listen port",
        param_type: ParamType::Integer,
        default_display: "8080",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "parallel",
        label: "Parallel Slots",
        description: "Number of parallel request slots",
        param_type: ParamType::Integer,
        default_display: "1",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "cont_batching",
        label: "Continuous Batching",
        description: "Enable continuous batching",
        param_type: ParamType::Bool,
        default_display: "on",
        category: "Server",
        is_typed_field: true,
    },
    ParamDef {
        key: "timeout",
        label: "Timeout",
        description: "Server request timeout in seconds",
        param_type: ParamType::Integer,
        default_display: "600",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "threads-http",
        label: "HTTP Threads",
        description: "Number of HTTP server threads",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "sleep-idle-seconds",
        label: "Sleep Idle (s)",
        description: "Seconds of idleness before server sleeps (-1=disabled)",
        param_type: ParamType::Integer,
        default_display: "-1",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "reuse-port",
        label: "Reuse Port",
        description: "Allow multiple sockets to bind to the same port",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "api-key",
        label: "API Key",
        description: "Comma-separated authentication keys",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "api-key-file",
        label: "API Key File",
        description: "File containing API keys (one per line)",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "alias",
        label: "Model Alias",
        description: "Model alias for API responses",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "tags",
        label: "Model Tags",
        description: "Model tags, comma-separated (informational)",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "api-prefix",
        label: "API Prefix",
        description: "URL prefix path without trailing slash",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-webui",
        label: "No WebUI",
        description: "Disable built-in web UI (WebUI is on by default)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "webui-mcp-proxy",
        label: "WebUI MCP Proxy",
        description: "Enable experimental MCP CORS proxy in the WebUI",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "metrics",
        label: "Metrics",
        description: "Enable Prometheus metrics endpoint",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "props",
        label: "Props",
        description: "Enable /props endpoint for changing global properties",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "slots",
        label: "Slots Endpoint",
        description: "Expose /slots monitoring endpoint",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "embedding",
        label: "Embedding",
        description: "Restrict to embedding-only mode",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "reranking",
        label: "Reranking",
        description: "Enable reranking endpoint",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-warmup",
        label: "No Warmup",
        description: "Disable model warmup run on startup (warmup is on by default)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "slot-prompt-similarity",
        label: "Slot Prompt Similarity",
        description: "Minimum prompt similarity for slot reuse (0=disabled)",
        param_type: ParamType::Float,
        default_display: "0.5",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "slot-save-path",
        label: "Slot Save Path",
        description: "Path to save slot KV cache",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "media-path",
        label: "Media Path",
        description: "Directory for loading local media files via file:// URLs",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "webui-config",
        label: "WebUI Config (JSON)",
        description: "JSON string providing default WebUI settings",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "webui-config-file",
        label: "WebUI Config File",
        description: "JSON file providing default WebUI settings",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "ssl-key-file",
        label: "SSL Key File",
        description: "Path to SSL private key file",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "ssl-cert-file",
        label: "SSL Cert File",
        description: "Path to SSL certificate file",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "embd-separator",
        label: "Embedding Separator",
        description: "Separator between embeddings (default: \\n)",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "cls-separator",
        label: "Classification Separator",
        description: "Separator for classification sequences (default: \\t)",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },
    ParamDef {
        key: "tools",
        label: "Tools (EXPERIMENTAL)",
        description: "Built-in tools to enable: read_file, file_glob_search, grep_search, exec_shell_command, write_file, edit_file, apply_diff, or 'all'",
        param_type: ParamType::String,
        default_display: "",
        category: "Server",
        is_typed_field: false,
    },

    // ── Chat ─────────────────────────────────────────────────────────────────
    ParamDef {
        key: "chat-template",
        label: "Chat Template",
        description: "Jinja chat template string",
        param_type: ParamType::String,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "chat-template-file",
        label: "Chat Template File",
        description: "Path to Jinja chat template file",
        param_type: ParamType::String,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "chat-template-kwargs",
        label: "Chat Template Kwargs",
        description: "JSON object with template parser parameters",
        param_type: ParamType::String,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-jinja",
        label: "No Jinja",
        description: "Disable Jinja template engine (Jinja is on by default)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-prefill-assistant",
        label: "No Prefill Assistant",
        description: "Disable prefilling assistant response if last message is from assistant",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "skip-chat-parsing",
        label: "Skip Chat Parsing",
        description: "Force pure content parser, skip tool and reasoning extraction",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "reasoning",
        label: "Reasoning",
        description: "Enable or disable reasoning/thinking in chat (auto/on/off)",
        param_type: ParamType::Enum(&["auto", "on", "off"]),
        default_display: "auto",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "reasoning-format",
        label: "Reasoning Format",
        description: "How to handle thought tags in output",
        param_type: ParamType::Enum(&["auto", "none", "deepseek", "deepseek-legacy"]),
        default_display: "auto",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "reasoning-budget",
        label: "Reasoning Budget",
        description: "Token budget for thinking (-1=unrestricted, 0=immediate end)",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "reasoning-budget-message",
        label: "Budget Message",
        description: "Message injected before end-of-thinking tag when budget is exhausted",
        param_type: ParamType::String,
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "pooling",
        label: "Pooling",
        description: "Embedding pooling type (none, mean, cls, last, rank)",
        param_type: ParamType::Enum(&["", "none", "mean", "cls", "last", "rank"]),
        default_display: "",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "special",
        label: "Special Tokens",
        description: "Output special tokens in the response",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "verbose-prompt",
        label: "Verbose Prompt",
        description: "Print verbose prompt before generation",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "spm-infill",
        label: "SPM Infill",
        description: "Use Suffix/Prefix/Middle infill pattern instead of Prefix/Suffix/Middle",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-escape",
        label: "No Escape",
        description: "Disable processing of escape sequences (\\n, \\t, etc.)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Chat",
        is_typed_field: false,
    },

    // ── Advanced: RoPE ───────────────────────────────────────────────────────
    ParamDef {
        key: "rope-scaling",
        label: "RoPE Scaling",
        description: "RoPE scaling type",
        param_type: ParamType::Enum(&["default", "none", "linear", "yarn"]),
        default_display: "default",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "rope-scale",
        label: "RoPE Scale",
        description: "RoPE context scaling factor",
        param_type: ParamType::Float,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "rope-freq-base",
        label: "RoPE Freq Base",
        description: "RoPE frequency base (0=auto from model)",
        param_type: ParamType::Float,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "rope-freq-scale",
        label: "RoPE Freq Scale",
        description: "RoPE frequency scaling factor (0=auto from model)",
        param_type: ParamType::Float,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: Speculative ────────────────────────────────────────────────
    ParamDef {
        key: "model-draft",
        label: "Draft Model",
        description: "Path to draft model for speculative decoding",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "spec-type",
        label: "Spec Type",
        description: "Speculative decoding type without a draft model",
        param_type: ParamType::Enum(&["", "ngram-cache", "ngram-simple", "ngram-map-k", "ngram-map-k4v", "ngram-mod"]),
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "draft-max",
        label: "Draft Max",
        description: "Max draft tokens per step (default: 16)",
        param_type: ParamType::Integer,
        default_display: "16",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "draft-min",
        label: "Draft Min",
        description: "Min draft tokens per step (default: 0)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "draft-p-min",
        label: "Draft P Min",
        description: "Min draft token probability for greedy (default: 0.75)",
        param_type: ParamType::Float,
        default_display: "0.75",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "spec-ngram-size-n",
        label: "N-gram Size N",
        description: "N-gram size N for ngram-simple/ngram-map speculative decoding",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "spec-ngram-size-m",
        label: "N-gram Size M",
        description: "N-gram size M for ngram-simple/ngram-map speculative decoding",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "spec-ngram-min-hits",
        label: "N-gram Min Hits",
        description: "Minimum hits for ngram-map speculative decoding",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "ctx-size-draft",
        label: "Draft Ctx Size",
        description: "Context size for draft model (0=from model)",
        param_type: ParamType::Integer,
        default_display: "0",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "n-gpu-layers-draft",
        label: "Draft GPU Layers",
        description: "Number of GPU layers for draft model",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "device-draft",
        label: "Draft Device",
        description: "Devices for draft model, comma-separated",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "threads-draft",
        label: "Draft Threads",
        description: "CPU threads for draft model generation",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "threads-batch-draft",
        label: "Draft Batch Threads",
        description: "CPU threads for draft model batch/prompt processing",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "override-tensor-draft",
        label: "Override Tensor (Draft)",
        description: "Override tensor buffer type for draft model: <pattern>=<type>,...",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "lookup-cache-static",
        label: "Lookup Cache (Static)",
        description: "Static lookup cache file for lookup decoding (read-only)",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "lookup-cache-dynamic",
        label: "Lookup Cache (Dynamic)",
        description: "Dynamic lookup cache file for lookup decoding (updated by generation)",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: LoRA & Control Vectors ─────────────────────────────────────
    ParamDef {
        key: "lora",
        label: "LoRA",
        description: "Path to LoRA adapter file",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "lora-scaled",
        label: "LoRA Scaled",
        description: "LoRA adapter with custom scale: path:scale",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "lora-init-without-apply",
        label: "LoRA Init Without Apply",
        description: "Load LoRA adapters without applying (apply later via POST /lora-adapters)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "control-vector",
        label: "Control Vector",
        description: "Comma-separated paths to control vector files",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "control-vector-scaled",
        label: "Control Vector Scaled",
        description: "Control vector with custom scale: FNAME:SCALE,...",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: Multimodal ─────────────────────────────────────────────────
    ParamDef {
        key: "mmproj",
        label: "Multimodal Projector",
        description: "Path to mmproj file for vision models",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "mmproj-url",
        label: "mmproj URL",
        description: "URL to download mmproj file",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "image-min-tokens",
        label: "Image Min Tokens",
        description: "Minimum number of tokens for image processing",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "image-max-tokens",
        label: "Image Max Tokens",
        description: "Maximum number of tokens for image processing",
        param_type: ParamType::Integer,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-mmproj-offload",
        label: "No mmproj Offload",
        description: "Disable GPU offload for multimodal projector",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "no-mmproj",
        label: "No mmproj Auto",
        description: "Disable auto-use of multimodal projector even if available",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: TTS ────────────────────────────────────────────────────────
    ParamDef {
        key: "model-vocoder",
        label: "Vocoder Model",
        description: "Path to vocoder model for audio/TTS generation",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "tts-use-guide-tokens",
        label: "TTS Guide Tokens",
        description: "Use guide tokens to improve TTS word recall",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Advanced: Logging ────────────────────────────────────────────────────
    ParamDef {
        key: "log-file",
        label: "Log File",
        description: "Path to log file",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "log-colors",
        label: "Log Colors",
        description: "Colored logging (auto detects terminal)",
        param_type: ParamType::Enum(&["auto", "on", "off"]),
        default_display: "auto",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "log-verbosity",
        label: "Verbosity",
        description: "Log verbosity level (0=generic, 1=error, 2=warning, 3=info, 4=debug)",
        param_type: ParamType::Enum(&["0", "1", "2", "3", "4"]),
        default_display: "3",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "verbose",
        label: "Verbose",
        description: "Set verbosity to maximum (log all messages)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "perf",
        label: "Perf Timings",
        description: "Print internal libllama performance timings",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "log-prefix",
        label: "Log Prefix",
        description: "Add prefix to log messages",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "log-timestamps",
        label: "Log Timestamps",
        description: "Add timestamps to log messages",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "offline",
        label: "Offline",
        description: "Prevent all network access, use cache only",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "profile",
        label: "Profile",
        description: "Enable cross-backend profiling (CPU, BLAS, CUDA)",
        param_type: ParamType::Bool,
        default_display: "off",
        category: "Advanced",
        is_typed_field: false,
    },
    ParamDef {
        key: "profile-output",
        label: "Profile Output",
        description: "Write profiling JSON output to file (default: stdout)",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },

    // ── Raw ──────────────────────────────────────────────────────────────────
    ParamDef {
        key: "__raw__",
        label: "Raw CLI Arguments",
        description: "Free-form CLI arguments not covered above (space-separated)",
        param_type: ParamType::String,
        default_display: "",
        category: "Advanced",
        is_typed_field: false,
    },
];
